### ISSUE TITLE
RA4 Encounter data invalid

### ISSUE THREAD

**Issue by djehring** [Somerset-SIDeR-Programme/sccr-demonstrator#4]
https://github.com/Somerset-SIDeR-Programme/sccr-demonstrator/blob/master/public/RA4/Encounter/9449303789.json

Invalid encounter.class representation (CodeableConcept):
 "class": {
          "display": "outpatient"
        },
should read  
 "class": {
          "text": "outpatient"
        },

"class": {
          "system": "http://hl7.org/fhir/v3/ActEncounterCode",
          "code": "EMER",
          "display": "emergency"
        }

should read

"class": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/v3/ActEncounterCode",
              "code": "EMER",
              "display": "emergency"
            }
          ]
        }

**Comment by Fdawgs** [comment]
Hi @djehring, in https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Encounter-1 the class has a [coding](http://hl7.org/fhir/stu3/datatypes.html#coding) data type and not a codeable concept, so not too sure on either of these changes?

**Comment by djehring** [comment]
@Fdawgs You are correct, ignore my correction
