### ISSUE TITLE
RA4 MedicationStatement data invalid

### ISSUE THREAD

**Issue by djehring** [Somerset-SIDeR-Programme/sccr-demonstrator#5]
MedicationStatement.medicationReference references a contained resource so the reference should use a hashtag

https://github.com/Somerset-SIDeR-Programme/sccr-demonstrator/blob/master/public/RA4/MedicationStatement/9449303789.json

"medicationReference": {
          "reference": "Medication/8"
        },

should read

"medicationReference": {
          "reference": "#8"
        },

**Comment by Fdawgs** [comment]
Thanks @djehring, have added this to my notes!
